package org.spitzig.androidMessageServer;

public enum ConnectionStatus {
	RECIEVING_ACTION,
	RECIEVING_SMIL,
	SENDING_KEY,
	RECIEVING_KEY,
	RECIEVING_COMMAND,
	RECIEVING_RESOURCE_DETAILS,
	RECIEVING_RESOURCE_DATA,
	SENDING_MESSAGE
}
